# Multi layer Neural Network

In [2]:
import numpy as np

In [5]:
inp = np.array([[0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]])
print("Input \n",inp)

out = np.array([[0,0,1,1]]).T
print("Output \n",out)

np.random.seed(1)
weight0 = 2*np.random.random((3,4)) - 1
weight1 = 2*np.random.random((4,1)) - 1
print("Weight0 \n",weight0)
print("Weight1 \n",weight1)

def sigmoid(inp):
    return 1/(1+np.exp(-inp))
def change(inp):
    return inp*(1-inp)

for i in range(2):
    inp0 = inp
    out0 = sigmoid(np.dot(inp0,weight0))  # inp dot w (inp(4,3)*w(3,4)) = 4 rows 4 column
    out1 = sigmoid(np.dot(out0,weight1))
    
    print("out0 \n",out0,"\nout1 \n",out1)
    
    err1 = out - out1
    
    if(i%10000) == 0:
        print("Error : ",str(np.mean(np.abs(err1))))
    
    err1_chng = err1 * change(out1)
    
    err0 = err1_chng.dot(weight1.T)
    
    print("Error0 \n",err0,"\nError1 \n",err1)
    
    err0_chng = err0 * sigmoid(out0)
    
    weight1 += np.dot(out0.T , err1_chng)
    weight0 += np.dot(inp0.T , err0_chng)

print("Output after train \n",out1)
print("Weight after train \n",weight1)
a = float(input("Enter First number: "))
b = float(input("Enter Second number: "))
c = float(input("Enter Third number: "))
d = float(input("Enter Fourth number: "))
arr = np.array([a,b,c,d])
brr = arr
print(brr.T)
My_out = sigmoid(np.dot(arr,weight1))
print("Query Output : ",My_out)

Input 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
Output 
 [[0]
 [0]
 [1]
 [1]]
Weight0 
 [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
Weight1 
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
out0 
 [[0.44856632 0.51939863 0.45968497 0.59156505]
 [0.28639589 0.32350963 0.31236398 0.51538526]
 [0.40795614 0.62674606 0.23841622 0.49377636]
 [0.25371248 0.42628115 0.14321233 0.41732254]] 
out1 
 [[0.47372957]
 [0.48895696]
 [0.54384086]
 [0.54470837]]
Error :  0.4685343254580603
Error0 
 [[ 0.0698116  -0.08931546  0.11163621 -0.04026629]
 [ 0.07221982 -0.09239648  0.1154872  -0.04165531]
 [-0.06689016  0.08557784 -0.10696451  0.03858124]
 [-0.06674228  0.08538864 -0.10672803  0.03849595]] 
Error1 
 [[-0.47372957]
 [-0.48895696]
 [ 0.45615914]
 [ 0.45529163]]
out0 
 [[0.45007457 0.51885601 0.46418602 0.59039665]
 [0.28839461 0.32260834 0.3183271  0.51346043]
 [0.39076888 0.

Enter First number:  1
Enter Second number:  0
Enter Third number:  1
Enter Fourth number:  0


[1. 0. 1. 0.]
Query Output :  [0.15879001]


In [ ]:
print("Shahin")