# My first Neural Net

In [2]:
import numpy as np

In [15]:
inp = np.array([[0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]])
print("Input \n",inp)

out = np.array([[0,0,1,1]]).T
print("Output \n",out)

np.random.seed(1)
weight = 2*np.random.random((3,1)) - 1
print("Weight \n",weight)

def sigmoid(inp):
    return 1/(1+np.exp(-inp))
def change(inp):
    return inp*(1-inp)

for i in range(10000):
    inp0 = inp
    out0 = sigmoid(np.dot(inp0,weight))
    
    err0 = out - out0
    
    err0_chng = err0 * change(out0)
    
    weight += np.dot(inp0.T , err0_chng)

print("Output after train \n",out0)

Input 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
Output 
 [[0]
 [0]
 [1]
 [1]]
Weight 
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Output after train 
 [[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
