# Multi layer Neural Network

In [1]:
import numpy as np

In [30]:
inp = np.array([[0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]])
print("Input \n",inp)

out = np.array([[0,0,1,1]]).T
print("Output \n",out)

np.random.seed(1)
weight0 = 2*np.random.random((3,4)) - 1
weight1 = 2*np.random.random((4,1)) - 1
print("Weight0 \n",weight0)
print("Weight1 \n",weight1)

def sigmoid(inp):
    return 1/(1+np.exp(-inp))
def change(inp):
    return inp*(1-inp)

for i in range(60000):
    inp0 = inp
    out0 = sigmoid(np.dot(inp0,weight0))
    out1 = sigmoid(np.dot(out0,weight1))
    
    err1 = out - out1
    
    if(i%10000) == 0:
        print("Error : ",str(np.mean(np.abs(err1))))
    
    err1_chng = err1 * change(out1)
    
    err0 = err1_chng.dot(weight1.T)
    
    err0_chng = err0 * sigmoid(out0)
    
    weight1 += np.dot(out0.T , err1_chng)
    weight0 += np.dot(inp0.T , err0_chng)

print("Output after train \n",out1)
print("Weight after train \n",weight1)
a = float(input("Enter First number: "))
b = float(input("Enter Second number: "))
c = float(input("Enter Third number: "))
d = float(input("Enter Fourth number: "))
arr = np.array([a,b,c,d])
brr = arr
print(brr.T)
My_out = sigmoid(np.dot(arr,weight1))
print("Query Output : ",My_out)

Input 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
Output 
 [[0]
 [0]
 [1]
 [1]]
Weight0 
 [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
Weight1 
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Error :  0.4685343254580603
Error :  0.006324468286497185
Error :  0.004277387928277676
Error :  0.003428985161420145
Error :  0.0029426366796411517
Error :  0.0026190602773365473
Output after train 
 [[0.00220195]
 [0.00228474]
 [0.99747733]
 [0.99747175]]
Weight after train 
 [[-5.01752326]
 [ 4.48402405]
 [-8.42509159]
 [ 1.53926461]]


Enter First number:  0
Enter Second number:  1
Enter Third number:  0
Enter Fourth number:  1


[0. 1. 0. 1.]
Query Output :  [0.99758416]
